### ISSUE TITLE
ffmpeg test failures

### ISSUE THREAD

**Issue by rekado** [wedesoft/aiscm#29]
I'm trying to upgrade the Guix package for aiscm, but I'm getting an unspecified test failure:

```
PASS: test_ffmpeg_out.scm - Writing a 2D array with 'write-image' returns the input array
PASS: test_ffmpeg_out.scm - Writing an image with 'write-image' returns the input image
make[4]: *** [Makefile:848: test_ffmpeg_out.log] Aborted
make[4]: *** Deleting file 'test_ffmpeg_out.log'
make[4]: *** Waiting for unfinished jobs....
```

This seems to be due to https://github.com/wedesoft/aiscm/commit/6eb20d6c3079dd59d5e1caedf3afc170dc0e84d3.
I tried building with ffmpeg 5.1, 4.4.2, and 3.4.11.  Building with 5.1 fails, and with 4.4 or 3.4 I'm getting the Abort while running tests.

Could you please tell me what version of ffmpeg is expected to work with the latest version of aiscm?
Thank you!

**Comment by wedesoft** [comment]
I use Debian 11 with FFmpeg 4.4. Unfortunately I didn't manage to adapt the code to FFmpeg 5.x so far.

**Comment by rekado** [comment]
Unfortunately I haven't been able to get past this error with FFmpeg 4.4.2.

**Comment by rekado** [comment]
I also tried with FFmpeg 4.3.4, which seems to be what Debian 11 provides; same error.

**Comment by wedesoft** [comment]
Ok, checked it on my system and it is not working. For some reason I thought I had tested it under Debian 11. Really sorry about that. Can you try Debian 10's ffmpeg version? It is [4.1.9](https://packages.debian.org/buster/ffmpeg).

**Comment by rekado** [comment]
Sadly, I see the same kind of failure with ffmpeg 4.1.9.

For the record here is the output of the ffmpeg configure phase:

[Uploading ffmpeg-configure…]()

**Comment by wedesoft** [comment]
Oh dear. I checked and I did some FFmpeg warning fixes without testing them. I have now reverted that change and released aiscm-0.24.2 as well. It works on Debian 11 (but not on the next Debian version) with FFmpeg 4.4.

```
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
...
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
```

**Comment by rekado** [comment]
Thank you, all is good now.  Guix commit 0d7f2469b550d42e48b7bba1aac27e777d758285 now provides "guile-aiscm" version 0.24.2; it's configured with OpenCV 4.5.4, Tensorflow 1.9.0, and FFmpeg 4.4.2 (among other things).

**Comment by wedesoft** [comment]
@rekado Thanks for packaging Aiscm and thanks for your perseverance.
